services:
  - type: web
    name: insightx-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port $PORT
    plan: free

  - type: web
    name: insightx-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
